version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on: ['elasticsearch']
    networks:
      - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    links:
    - elasticsearch
    - web
    volumes:
    - ~/pipeline/:/usr/share/logstash/pipeline/
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
    - esnet
    depends_on: 
    - elasticsearch
    - web
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "43434:5601"
    networks:
    - esnet
    depends_on: ['elasticsearch']
networks:
  esnet:
